





 





<!doctype html>
<html>
<head>
    






 





<meta charset="UTF-8">
<title>上海市闵行区教育学院</title>
<link rel="apple-touch-icon-precomposed" sizes="32x32" href="https://jyxyfiles.mhedu.sh.cn/ftpfiles/dcpfiles/mainpicture/ico_jyxy.ico">
<link rel="shortcut icon" href="https://jyxyfiles.mhedu.sh.cn/ftpfiles/dcpfiles/mainpicture/ico_jyxy.ico">
<script src="/static/vue/jquery-3.6.0.min.js"></script><script type="text/javascript" src="/static/vue/jquery-migrate.min.js"></script>
<script src="/static/js/jquery.SuperSlide.js?V1.0"></script>
<script src="/static/js/layer/layer.js"></script>
<script src="/static/js/idealdcp/utils/Utils.js"></script>
<script type="text/javascript" src="/static/js/ueditor/ueditor.parse.js"></script>
<script type="text/javascript" src="/static/js/jquery-qrcode-master/jquery.qrcode.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/static/extranet/mhedu/xl/css/style.css">
</head>
<body id="index">
<div id="header">

    






 






<div id="top">

</div>
<div id="nav">
    <ul class="menu">
        <li><a target='_blank' href="/extranet/web/index/index.action">学院首页</a></li>
        <li class="current"><a target='_blank' href="xl.action">本站首页</a></li>
        
            

        
            
                <li >
                    <a target='_blank' href="xl!more.action?code=EDXW.004.001">教学研究</a>
                </li>
            

        
            
                <li >
                    <a target='_blank' href="xl!more.action?code=EDXW.004.002">测评服务</a>
                </li>
            

        
            
                <li >
                    <a target='_blank' href="xl!more.action?code=EDXW.004.003">科普推广</a>
                </li>
            

        
        <li><a target='_blank'  href="xl!feedback.action?code=XLJK">心理健康</a></li>
    </ul>
</div>
</div>
<div class="indexwhite"></div>
<div id="main">
	<div class="mainbox cl">
		<div class="mleft">
			<div class="toptitle">
				新闻动态 <em>News</em>
			</div>
			<div class="mlbox">
				<div class="topnews cl">
                    
                    	
	                        <div class="newspic">
	                            <a target='_blank' href="xl!info.action?id=ff80808192b7eaad019399921c1018dd&areaCode=JYXY_XLJK_XWDT">
	                                <img src="https://jyxyfiles.mhedu.sh.cn/ftpfiles/dcpfiles/8a9c1a005cce76e5015cd2e970790651/app/XYXW/allArea/main/2024/12/sub_53844990fb29426ebf449d71b889b575.jpg" height="206" width="309" alt="">
	                            </a>
	                        </div>
	                        <div class="newsinfo">
	                            <h6>2024-12-05</h6>

                                <h3><a target="_blank" title="“激活内在动力 新时代学校生涯教育的路径探索”闵行区生涯教育市级展示研讨活动圆满举行"
                                       href="xl!info.action?id=ff80808192b7eaad019399921c1018dd&areaCode=JYXY_XLJK_XWDT">“激活内在动力 新时代学校生涯教育的路径探索”闵行区生涯教育市级展示研讨活动圆满举行</a>
                                </h3>
	                            <p>
2024年12月4日，为深入贯彻《上海市教育委员会关于加强中小学生涯教育的指导意见》，积极探索区域中小学生涯教育的新方法，旨在促进学生全面而幸福的成长，由闵行区教育局、闵行区教育学院共同主办的“激活内在动力 新时代学校生涯教育的路径探索”闵行区生涯教育市级展示研讨活动，在上海市闵行区浦航实验中学隆重举办。
上海市中小学心理辅导协会理事长沈之菲教授、上海市教育科学研究院德育研究院杨彦平研究员、上海市闵行区教育学院贾永春副院长、上海市闵行区教育局普教一科褚琛婷老师等出席了会议，此外上海市各区心理教研员、学校德育主任、生涯教师、心理教师、学科教师等200多人参加会议。会议由闵行区教育学院徐晶星老师主持。
教学展示与研讨
会议前部分，全体与会老师观摩上海市闵行区浦航实验中学精心设计生涯教育融合课堂教学的道德与法治课《“职”存高远 敬业乐业》、心理健康教育课《理想的职业》、主题班会《家族职业树之我的未来不是梦》、项目化学习课《学校英语节汇演活动创意设计》、拓展课《职业规划——“植”梦未来》，体现了生涯教育与学科教学的融合性的设计与实施。
区域总结与反思
上海市闵行区教育学院李攀老师详细介绍了自2013年起，闵行区中小学生涯教育的实践探索历程。李老师强调，生涯教育指导理念和政策文件要求，转化为日常、具体的教育实践，形成可复制的操作方案，是生涯教育生根落地的根本所在。李老师还提到，闵行区在平台搭建、资源建设、队伍培育等方面不断开拓的努力，以及经由生涯教育学校和学生的收获和成长。
学校交流与表彰
上海市闵行区浦航实验中学谌海兰校长分享了“看见优势 赋能成长”多路径探索的初中生生涯教育策略。谌校长介绍了学校如何通过生涯教育帮助学生认识自我，发现兴趣和潜能，学会选择，规划未来。谌校长强调，生涯教育不仅仅是职业指导，它关乎学生的自我认识、社会理解和生涯规划。上海市莘庄中学张乐副校长聚焦高中段的生涯教育学科融合实践探索，分享了学校在生涯教育推进过程中的实践经验与感受。张副校长提到，教育教学是科学的事情，要遵循孩子成长与发展规律，重视学生发展的核心素养。学校正在探索如何将学科教学与生涯教育无痕融合，以支持学生自我探索和促进教师专业发展。
会上，还表彰2024年闵行区生涯教育实践项目优秀校和2024年闵行区生涯教育实践项目优秀论文获得者。
区域启动与推进
闵行区教育学院贾永春副院长介绍了2025年闵行区生涯教育推进计划。贾院长提到，闵行区将继续拓展生涯教育实施途径，激活师生成长和发展的内在动力，让更多的学生、学校、教师从中受益。贾院长还强调了AI赋能教师导育能力提升的创新尝试，这将为生涯教育带来新的活力。
专家指导与引领
上海市中小学心理辅导协会理事长沈之菲教授对闵行区的生涯教育进行了深入的专家点评与指导，特别强调了该区生涯教育在厚度、宽度、深度及温度方面的显著特点。其中，厚度彰显于生涯教育的持续推动力与创新精神；宽度则体现在生涯教育内容的多元化；深度则反映在生涯培训的系统化与分层次分类上；而温度则表现在教师与学生对生涯教育的热忱投入与成长。
上海市教育科学研究院德育研究院的杨彦平研究员寄语闵行区生涯教育持续深入探索，致力于打造具有特色的教育模式，以期取得更多成果，并致力于培养杰出的教育名师。
本次会议是对闵行区推进生涯教育十年的一个回顾，也是一个新的十年的开启。在新的时代背景下，希望区域内更多的学校参与其中，与我们一道，进一步拓展生涯教育实施途径，让更多的学生、学校、教师从中受益，真正激活师生成长和发展的内在动力。</p>
	                            <div class="nop"><a target='_blank' href="xl!info.action?id=ff80808192b7eaad019399921c1018dd&areaCode=JYXY_XLJK_XWDT" class="vmore">+ 查看详情</a> <a target='_blank' href="xl!more.action?areaCode=JYXY_XLJK_XWDT" class="alllink">+ 全部动态</a></div>
	                        </div>
                        
                    
                    	
                    
                    	
                    
                    	
                    
                    	
                    
                    	
                    
				</div>
				<div class="newslistcon">
					<ul class="nlist cl">
                        
                            <li>
                                <h6>2024-12-30</h6>

                                <p><a target='_blank' title=" 流动共研 助力成长  —— 记小学段心理教师流动听课活动"
                                      href="xl!info.action?id=ff80808192b7ebe6019416cc6d5621d9&areaCode=JYXY_XLJK_XWDT"> 流动共研 助力成长  —— 记小学段心理教师流动听课活动</a>
                                </p>
                            </li>
                        
                            <li>
                                <h6>2024-12-27</h6>

                                <p><a target='_blank' title="和谐包容、自我关怀——闵行区初中心理教学研讨暨青春期教育研讨活动在文来初中举行"
                                      href="xl!info.action?id=ff80808192b7eaad0194068cb76e21d3&areaCode=JYXY_XLJK_XWDT">和谐包容、自我关怀——闵行区初中心理教学研讨暨青春期教育研讨活动在文来初中举行</a>
                                </p>
                            </li>
                        
                            <li>
                                <h6>2024-12-20</h6>

                                <p><a target='_blank' title="聚焦学业困扰 提升学生抗挫力 ——记闵行区小学心理公开课教学研讨活动"
                                      href="xl!info.action?id=ff80808192b7ebe60193e26d9f3f1e91&areaCode=JYXY_XLJK_XWDT">聚焦学业困扰 提升学生抗挫力 ——记闵行区小学心理公开课教学研讨活动</a>
                                </p>
                            </li>
                        
                            <li>
                                <h6>2024-12-13</h6>

                                <p><a target='_blank' title="五育润心，让每个孩子健康成长——七宝三中承办上海市中小学心理健康教育示范校展示活动"
                                      href="xl!info.action?id=ff80808192b7ebe60193befd6cc01b21&areaCode=JYXY_XLJK_XWDT">五育润心，让每个孩子健康成长——七宝三中承办上海市中小学心理健康教育示范校展示活动</a>
                                </p>
                            </li>
                        
                            <li>
                                <h6>2024-12-12</h6>

                                <p><a target='_blank' title="拓展视野，照亮生涯——记闵行区中小学导育系统之生涯辅导力培训项目生涯卡牌与高考志愿填报实操培训"
                                      href="xl!info.action?id=ff80808192b7eaad0193bd6a548c1c21&areaCode=JYXY_XLJK_XWDT">拓展视野，照亮生涯——记闵行区中小学导育系统之生涯辅导力培训项目生涯卡牌与高考志愿填报实操培训</a>
                                </p>
                            </li>
                        
                            <li>
                                <h6>2024-12-06</h6>

                                <p><a target='_blank' title="幸福青春期，赋能心成长 ——闵行区初中心理教学研讨暨七宝镇首届青年骨干（心理）基地展示活动在七宝文来学校举行"
                                      href="xl!info.action?id=ff80808192b7ebe601939a061d2f1707&areaCode=JYXY_XLJK_XWDT">幸福青春期，赋能心成长 ——闵行区初中心理教学研讨暨七宝镇首届青年骨干（心理）基地展示活动在七宝文来学校举行</a>
                                </p>
                            </li>
                        
					</ul>
				</div>
			</div>
		</div>
		<div class="mright">
			<div class="topintro">
				<h2>欢迎进入</h2>
				<div class="topintrocon">
                    
                        <h5> 流动共研 助力成长  —— 记小学段心理教师流动听课活动</h5>
                        <div class="introcon">
                            <p>为进一步提升区域小学段心理教师的心理辅导课授课能力，本学期流动听课活动在教研员徐涛老师的带领下持续开展， 本次活动吸引了七位老师积极申报，涵盖了不同教龄和教学经验层次的教师，充分体现了区域内心理教师们追求专业进步的热情。活动分为两轮进行，确保每位参与的教师都能得到针对性的指导和充分的锻炼机会。在第一轮流动听课中，主要面向那些渴望通过这一活动提升自身教学能力的老师。小学心理教研员徐涛老师和小学心理健康教育中心组、核心组的全体老师深入课堂，进行全面的听课与指导。从教案的设计到课堂教学的实施，每一个环节都不落下。老师们认真记录教学过程中的每一个细节，课后与授课教师进行深入交流，指出优点与不足，并提出切实可行的改进建议。授课教师们虚心接受意见，积极调整教学策略，为下一次的课堂教学不断优化做准备，在反复的磨课过程中，教学能力得到了提升。第二轮则聚焦于五位申请公开课的老师。这一轮的要求更为严格，指导也更加精细。中心组老师、核心组老师以及教研员不仅关注教学内容的准确性和丰富性，更注重教学方法的多样性和创新性，以及与学生互动的有效性。授课老师们也全力以赴，精心准备每一堂课，反复打磨教学细节，力求呈现出最精彩、最优质的心理辅导课。同时，为了让老师们能够在不同的教学环境中积累经验，还安排了听课老师到中心组、核心组老师所在学校借班上课，进一步拓宽了教学视野，增强了应对不同教学情境的能力。通过这一学期的流动听课活动，促进小学心理教师团队形成了良好的交流研磨氛围。不同梯队的老师都在这个过程中收获满满，新教师们在前辈们的指导下快速入门，掌握了心理辅导课的基本授课技巧；有一定经验的教师则突破了教学瓶颈，在教学方法和课程设计上有了新的创新和提升；而骨干教师们也在指导他人的过程中，进一步巩固了自己的专业知识，实现了教学相长。

</p>
                            <div class="intromore"><a target='_blank' href="xl!info.action?id=ff80808192b7ebe6019416cc6d5621d9&areaCode=JYXY_XLJK" class="vmore">+ 查看详情</a></div>
                        </div>
                    
				</div>
			</div>
		</div>
	</div>
	<div class="mbot">
		<div class="mbotbox cl">
			<div class="mbleft">
				<div class="schoollink">
					<div class="mbtitle">
						<span class="fr"><select name="" id="" class="msele">
							<option value="">上海市心理健康教育达标校</option>
						</select></span>
						学校掠影 <em>Schools</em>
					</div>
					<div class="schoollinkcon">
						<ul class="slist cl">
						
							
						</ul>
					</div>
				</div>
			</div>
			<div class="mbright">
                






 





<h3>教研平台登录 <em>Login</em></h3>
<ul class="mrlist">
    <li><a href="#"><img src="/static/extranet/mhedu/xl/images/m1.jpg" height="48" width="285" alt=""></a></li>
    <li><a href="#"><img src="/static/extranet/mhedu/xl/images/m2.jpg" height="48" width="285" alt=""></a></li>
    <li><a href="#"><img src="/static/extranet/mhedu/xl/images/m3.jpg" height="48" width="285" alt=""></a></li>
</ul>
			</div>
		</div>
	</div>
</div>
<div id="friendlink">
	<div class="friendlinkcon cl">
		<span class="fr">
			<select class="sele" name="" style="color: #000;" >
				
			</select>
			<select class="sele" name="" style="color: #000;" >
				
			</select>
		</span>
		<h2>友情链接</h2>
	</div>
</div>
<script type="text/javascript">
if(navigator.userAgent.indexOf("Safari")>0&&navigator.userAgent.indexOf("Chrome")==-1){
	$(".sele").click(function(){
		var url=$(this).val();
		if(url)
			window.open(url);
		
	});
}else{
	$(".sele").change(function(){
		var url=$(this).val();
		if(url)
			window.open(url);
		
	});
}

</script>






 





<div id="footer">
    <div class="copyright">
        <p class="bmenu"><a
                href="/extranet/web/mhedu/xx!oriented.action?catalogCode=JYXY_XXGK_LXWM">联系我们</a>
            |
            <a href="/extranet/web/mhedu/xx!oriented.action?catalogCode=JYXY_XXGK_BQSM">版权声明</a>
            |
            <a href="/extranet/web/mhedu/xx!LeavingMessare.action">我要留言</a></p>

        <p>版权所有 上海市闵行区教育学院 （工信部备案号:沪ICP备05012047号）
            <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31011202005311"
               style="text-decoration:none;height:20px;line-height:20px;">
                <img src="/static/extranet/mhedu/index/images/pilice.png"/>
                <span style="height:20px;line-height:20px;color:#fff;">沪公网安备 31011202005311号</span>
            </a>
        </p>

        <p>地址：上海市闵行区紫龙路835号 邮编：200241 电话：021-34728865</p>
        <span id="_ideConac" class="blogo" style="margin-top: -5px;">
            <a href="http://bszs.conac.cn/sitename?method=show&amp;id=2907016072AE5269E053012819ACF339" target="_blank">
                <img id="imgConac" vspace="0" hspace="0" border="0" src="https://jyxyfiles.mhedu.sh.cn/ftpfiles/dcpfiles/image/blue.png"
                     data-bd-imgshare-binded="1">
            </a>
        </span>
    </div>
</div>
</body>
</html>